# Generated by Django 4.1.3 on 2023-03-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boxes',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('box_name', models.CharField(max_length=100)),
                ('box_metal', models.CharField(max_length=100)),
                ('box_total_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('box_added_date', models.DateTimeField(auto_now_add=True)),
                ('box_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='boxes_sale_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item_sale_type', models.CharField(max_length=100)),
                ('item_sale_12', models.CharField(max_length=10)),
                ('sale_id', models.CharField(max_length=10)),
                ('box_updated_date', models.DateTimeField(auto_now_add=True)),
                ('box_id', models.ForeignKey(db_column='box_id', on_delete=django.db.models.deletion.PROTECT, to='boxes.boxes')),
            ],
        ),
        migrations.CreateModel(
            name='boxes_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=100)),
                ('box_added_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('box_existed_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('box_total_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item_purchase_12', models.CharField(max_length=10)),
                ('purchase_id', models.CharField(max_length=10)),
                ('box_updated_date', models.DateTimeField(auto_now_add=True)),
                ('box_id', models.ForeignKey(db_column='box_id', on_delete=django.db.models.deletion.PROTECT, to='boxes.boxes')),
            ],
        ),
    ]
