# Generated by Django 4.1.3 on 2023-03-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchases2',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=30)),
                ('inv_date', models.CharField(max_length=50)),
                ('metal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('Purity', models.CharField(choices=[('99.9', '99.9'), ('91.6', '91.6'), ('92.5', '92.5'), ('90.0', '90.0'), ('85.0', '85.0'), ('88 KDM', '88 KDM'), ('85 kDM', '85 KDM'), ('80.0', '80.0'), ('78.0', '78.0'), ('75.0', '75.0'), ('70.0', '70.0')], max_length=15)),
                ('HSN_SAC_Code', models.CharField(choices=[('7113', '7113'), ('7114', '7114')], max_length=4)),
                ('item_purchase_12', models.CharField(max_length=10)),
                ('less_weight', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rounded_off', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('declaration', models.CharField(max_length=100)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unsettled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_deleted', models.BooleanField(default=False)),
                ('delivery_mode', models.CharField(max_length=50)),
                ('box_id', models.ForeignKey(db_column='box_id', on_delete=django.db.models.deletion.PROTECT, to='boxes.boxes')),
                ('vendor_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, to='vendors.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='purchases',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=30)),
                ('inv_date', models.CharField(max_length=50)),
                ('metal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('Purity', models.CharField(choices=[('99.9', '99.9'), ('91.6', '91.6'), ('92.5', '92.5'), ('90.0', '90.0'), ('85.0', '85.0'), ('88 KDM', '88 KDM'), ('85 kDM', '85 KDM'), ('80.0', '80.0'), ('78.0', '78.0'), ('75.0', '75.0'), ('70.0', '70.0')], max_length=15)),
                ('HSN_SAC_Code', models.CharField(choices=[('7113', '7113'), ('7114', '7114')], max_length=4)),
                ('item_purchase_12', models.CharField(max_length=10)),
                ('less_weight', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rounded_off', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('declaration', models.CharField(max_length=100)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unsettled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_deleted', models.BooleanField(default=False)),
                ('delivery_mode', models.CharField(max_length=50)),
                ('box_id', models.ForeignKey(db_column='box_id', on_delete=django.db.models.deletion.PROTECT, to='boxes.boxes')),
                ('vendor_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, to='vendors.vendors')),
            ],
        ),
    ]
