# Generated by Django 4.1.3 on 2023-03-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_address2', models.CharField(max_length=200)),
                ('cus_emailid', models.CharField(max_length=200, null=True)),
                ('cus_gstin', models.CharField(max_length=15, null=True)),
                ('cus_state', models.CharField(max_length=100)),
                ('cus_state_code', models.CharField(max_length=100)),
                ('cus_mobile_no', models.CharField(max_length=15)),
                ('cus_mobile_no2', models.CharField(max_length=15, null=True)),
                ('cus_pan_no', models.CharField(max_length=10, null=True)),
                ('cus_aadhar_no', models.CharField(max_length=12, null=True)),
                ('cus_kyc', models.CharField(max_length=100)),
                ('cus_added_date', models.DateTimeField(auto_now_add=True)),
                ('cus_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
