# Generated by Django 4.1.3 on 2023-03-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='box_id',
            field=models.ForeignKey(db_column='box_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='boxes.boxes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales2',
            name='box_id',
            field=models.ForeignKey(db_column='box_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='boxes.boxes'),
            preserve_default=False,
        ),
    ]
