# Generated by Django 4.1.3 on 2023-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_huid_sales2_huid_alter_sales_cal_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='weight_with_tag',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales2',
            name='weight_with_tag',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales2',
            name='old_items_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
